name: bci_ai
channels:
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=2.1.0
  - aom=3.6.0
  - blas=1.0
  - blinker=1.8.2
  - blosc=1.21.3
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.9.24
  - cairo=1.16.0
  - certifi=2024.8.30
  - cffi=1.17.1
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=3.4.0
  - click=8.1.7
  - contourpy=1.2.0
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cuda-version=12.6
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - dbus=1.13.18
  - eigen=3.4.0
  - expat=2.6.3
  - ffmpeg=4.2.2
  - filelock=3.16.1
  - flask=3.0.3
  - fontconfig=2.14.1
  - fonttools=4.51.0
  - freetype=2.12.1
  - gdk-pixbuf=2.42.10
  - giflib=5.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - gmp=6.2.1
  - gnutls=3.6.15
  - graphite2=1.3.14
  - grpcio=1.62.2
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h2=4.1.0
  - harfbuzz=4.3.0
  - hdf5=1.12.1
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=73.1
  - idna=3.10
  - imagecodecs=2023.1.23
  - imageio=2.33.1
  - importlib-metadata=8.5.0
  - intel-openmp=2023.1.0
  - itsdangerous=2.2.0
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - jxrlib=1.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lazy_loader=0.4
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - lerc=3.0
  - libabseil=20240116.2
  - libaec=1.0.4
  - libavif=0.11.1
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.11.1.6
  - libcups=2.4.2
  - libcurand=10.3.7.77
  - libcurl=7.88.1
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.78.4
  - libgomp=14.2.0
  - libgrpc=1.62.2
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=12.17
  - libprotobuf=4.25.3
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libvpx=1.7.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.13.1
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - llvm-openmp=12.0.1
  - lz4-c=1.9.4
  - markdown=3.6
  - markupsafe=3.0.2
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.10
  - mkl_random=1.2.7
  - mpmath=1.3.0
  - mysql=5.7.24
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.3
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - opencv=4.10.0
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openslide=3.4.1
  - openssl=3.3.2
  - packaging=24.1
  - pandas=2.2.2
  - pcre2=10.42
  - pillow=10.4.0
  - pip=24.2
  - pixman=0.40.0
  - ply=3.11
  - protobuf=4.25.3
  - pybind11-abi=5
  - pycparser=2.22
  - pyparsing=3.1.2
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.12.7
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - pytorch=2.5.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.2
  - qt-main=5.15.2
  - re2=2022.04.01
  - readline=8.2
  - requests=2.32.3
  - scikit-image=0.24.0
  - scikit-learn=1.5.1
  - scipy=1.13.1
  - setuptools=75.1.0
  - sip=6.7.12
  - six=1.16.0
  - snappy=1.2.1
  - sqlite=3.45.3
  - sympy=1.13.3
  - tbb=2021.5.0
  - tensorboard=2.18.0
  - tensorboard-data-server=0.7.0
  - threadpoolctl=3.5.0
  - tifffile=2023.4.12
  - tk=8.6.14
  - torchtriton=3.1.0
  - torchvision=0.20.1
  - tornado=6.4.1
  - tqdm=4.66.5
  - typing_extensions=4.12.2
  - tzdata=2024b
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - werkzeug=3.1.1
  - wheel=0.44.0
  - x264=1!157.20191217
  - xz=5.4.6
  - yaml=0.2.5
  - zfp=1.0.0
  - zipp=3.20.2
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - openslide-python==1.4.1
